import { Company, IndustryFilter, PartnershipLevelFilter } from './types';

// Mock company data
export const companiesData: Company[] = [
  {
    id: 1,
    name: 'TechSolutions Inc.',
    logo: '/images/companies/tech-solutions.jpg',
    description:
      'A leading technology solutions provider focused on digital transformation, cloud services, and enterprise software development.',
    industry: 'Information Technology',
    location: 'San Francisco, CA',
    website: 'https://www.techsolutions.example',
    yearFounded: 2005,
    employeeCount: '1,000-5,000',
    partnershipLevel: 'Gold',
    partnerSince: 2018,
    tags: ['Cloud Computing', 'Digital Transformation', 'Enterprise Software'],
    featured: true,
  },
  {
    id: 2,
    name: 'InnovateCorp',
    logo: '/images/companies/innovate-corp.jpg',
    description:
      'Innovation-focused technology company specializing in AI, machine learning, and data analytics solutions.',
    industry: 'Artificial Intelligence',
    location: 'Boston, MA',
    website: 'https://www.innovatecorp.example',
    yearFounded: 2012,
    employeeCount: '500-1,000',
    partnershipLevel: 'Silver',
    partnerSince: 2019,
    tags: ['AI', 'Machine Learning', 'Data Analytics', 'Research'],
  },
  {
    id: 3,
    name: 'GreenTech Solutions',
    logo: '/images/companies/green-tech.jpg',
    description:
      'Sustainable technology company developing eco-friendly solutions for businesses and consumers.',
    industry: 'Clean Technology',
    location: 'Portland, OR',
    website: 'https://www.greentech.example',
    yearFounded: 2015,
    employeeCount: '100-500',
    partnershipLevel: 'Bronze',
    partnerSince: 2020,
    tags: ['Sustainability', 'Clean Energy', 'Green Technology'],
  },
  {
    id: 4,
    name: 'FinSecurity Group',
    logo: '/images/companies/fin-security.jpg',
    description:
      'Financial technology company providing secure payment processing, fraud detection, and cybersecurity services.',
    industry: 'FinTech',
    location: 'New York, NY',
    website: 'https://www.finsecurity.example',
    yearFounded: 2010,
    employeeCount: '1,000-5,000',
    partnershipLevel: 'Gold',
    partnerSince: 2017,
    tags: ['Cybersecurity', 'Finance', 'Fraud Detection', 'Payments'],
  },
  {
    id: 5,
    name: 'HealthPlus Systems',
    logo: '/images/companies/health-plus.jpg',
    description:
      'Healthcare technology company creating innovative solutions for patient care, telemedicine, and medical record management.',
    industry: 'Healthcare Technology',
    location: 'Chicago, IL',
    website: 'https://www.healthplus.example',
    yearFounded: 2008,
    employeeCount: '500-1,000',
    partnershipLevel: 'Silver',
    partnerSince: 2019,
    tags: ['Healthcare', 'Telemedicine', 'Medical Records', 'Patient Care'],
    featured: true,
  },
  {
    id: 6,
    name: 'CreativeLabs',
    logo: '/images/companies/creative-labs.jpg',
    description:
      'Creative technology studio focused on digital design, UX/UI, animation, and interactive experiences.',
    industry: 'Digital Design',
    location: 'Los Angeles, CA',
    website: 'https://www.creativelabs.example',
    yearFounded: 2016,
    employeeCount: '50-100',
    partnershipLevel: 'Bronze',
    partnerSince: 2021,
    tags: ['UX/UI', 'Animation', 'Digital Design', 'Interactive Media'],
  },
  {
    id: 7,
    name: 'Axiomy',
    logo: '/images/companies/axiomy.jpg',
    description:
      'Advanced software solutions provider specializing in enterprise architecture and digital transformation.',
    industry: 'Information Technology',
    location: 'Sofia, Bulgaria',
    website: 'https://www.axiomy.example',
    yearFounded: 2018,
    employeeCount: '100-500',
    partnershipLevel: 'Silver',
    partnerSince: 2022,
    tags: ['Enterprise Architecture', 'Digital Transformation', 'Software Development'],
  },
  {
    id: 8,
    name: 'Valtech',
    logo: '/images/companies/valtech.jpg',
    description:
      'Global digital agency providing end-to-end technology services, digital experience, and innovation solutions.',
    industry: 'Digital Services',
    location: 'Paris, France',
    website: 'https://www.valtech.example',
    yearFounded: 1993,
    employeeCount: '1,000-5,000',
    partnershipLevel: 'Gold',
    partnerSince: 2020,
    tags: ['Digital Experience', 'Innovation', 'Technology Services'],
    featured: true,
  },
  {
    id: 9,
    name: 'Besco',
    logo: '/images/companies/besco.jpg',
    description:
      'Business process optimization and consulting firm focused on operational excellence and digital workflows.',
    industry: 'Business Consulting',
    location: 'Sofia, Bulgaria',
    website: 'https://www.besco.example',
    yearFounded: 2015,
    employeeCount: '50-100',
    partnershipLevel: 'Bronze',
    partnerSince: 2023,
    tags: ['Business Process', 'Consulting', 'Operational Excellence'],
  },
  {
    id: 10,
    name: 'Bul-ai',
    logo: '/images/companies/bulailogo.png',
    description:
      'Bulgarian artificial intelligence company developing cutting-edge AI solutions for various industries.',
    industry: 'Artificial Intelligence',
    location: 'Sofia, Bulgaria',
    website: 'https://www.bul-ai.example',
    yearFounded: 2019,
    employeeCount: '50-100',
    partnershipLevel: 'Silver',
    partnerSince: 2023,
    tags: ['AI', 'Machine Learning', 'Innovation', 'Research'],
  },
  {
    id: 11,
    name: 'WealthBulgaria',
    logo: '/images/companies/wblogo.webp',
    description:
      'Leading Bulgarian financial services company providing wealth management and investment solutions.',
    industry: 'FinTech',
    location: 'Sofia, Bulgaria',
    website: 'https://www.wealthbulgaria.example',
    yearFounded: 2012,
    employeeCount: '100-500',
    partnershipLevel: 'Gold',
    partnerSince: 2021,
    tags: ['Wealth Management', 'Investment', 'Financial Services'],
  },
  {
    id: 12,
    name: 'Startup a 5.0',
    logo: '/images/companies/startup-a-5.jpg',
    description:
      'Innovation accelerator and startup incubator focused on next-generation technology ventures.',
    industry: 'Venture Capital',
    location: 'Sofia, Bulgaria',
    website: 'https://www.startup-a-5.example',
    yearFounded: 2020,
    employeeCount: '10-50',
    partnershipLevel: 'Bronze',
    partnerSince: 2023,
    tags: ['Startup Acceleration', 'Innovation', 'Venture Capital'],
  },
  {
    id: 13,
    name: 'Oximo',
    logo: '/images/companies/oximologo.jpg',
    description:
      'Technology optimization and system integration company specializing in enterprise solutions.',
    industry: 'Information Technology',
    location: 'Sofia, Bulgaria',
    website: 'https://www.oximo.example',
    yearFounded: 2016,
    employeeCount: '100-500',
    partnershipLevel: 'Silver',
    partnerSince: 2022,
    tags: ['System Integration', 'Enterprise Solutions', 'Technology Optimization'],
  },
  {
    id: 14,
    name: 'Devids',
    logo: '/images/companies/devids.jpg',
    description:
      'Software development company focused on custom web applications, mobile solutions, and digital platforms.',
    industry: 'Information Technology',
    location: 'Sofia, Bulgaria',
    website: 'https://www.devids.example',
    yearFounded: 2017,
    employeeCount: '50-100',
    partnershipLevel: 'Bronze',
    partnerSince: 2023,
    tags: ['Web Development', 'Mobile Apps', 'Custom Software'],
  },
  {
    id: 15,
    name: 'MBrand',
    logo: '/images/companies/mbrand.jpg',
    description:
      'Creative marketing and branding agency specializing in digital marketing, brand identity, and creative campaigns.',
    industry: 'Digital Marketing',
    location: 'Sofia, Bulgaria',
    website: 'https://www.mbrand.example',
    yearFounded: 2014,
    employeeCount: '50-100',
    partnershipLevel: 'Bronze',
    partnerSince: 2023,
    tags: ['Digital Marketing', 'Brand Identity', 'Creative Campaigns'],
  },
] as const;

// Industry filter options
export const industryFilters: IndustryFilter[] = [
  { id: 'all', name: 'All Industries' },
  { id: 'information-technology', name: 'Information Technology' },
  { id: 'artificial-intelligence', name: 'Artificial Intelligence' },
  { id: 'fintech', name: 'FinTech' },
  { id: 'healthcare', name: 'Healthcare' },
  { id: 'design', name: 'Digital Design' },
  { id: 'digital-services', name: 'Digital Services' },
  { id: 'business-consulting', name: 'Business Consulting' },
  { id: 'venture-capital', name: 'Venture Capital' },
  { id: 'digital-marketing', name: 'Digital Marketing' },
];

// Partnership level filter options
export const partnershipLevelFilters: PartnershipLevelFilter[] = [
  { id: 'all', name: 'All Partners' },
  { id: 'gold', name: 'Gold Partners' },
  { id: 'silver', name: 'Silver Partners' },
  { id: 'bronze', name: 'Bronze Partners' },
];
