import { Company } from './types';

// New company data that uses actual images from public/images/companies
export const companiesData: Company[] = [
  {
    id: 1,
    name: 'Devids',
    logo: '/images/companies/Devids-logo.png',
    description:
      'Innovative software development company specializing in modern web applications, mobile solutions, and digital transformation services.',
    industry: 'Software Development',
    location: 'Sofia, Bulgaria',
    website: 'https://www.devids.com',
    yearFounded: 2020,
    employeeCount: '10-50',
    partnershipLevel: 'Gold',
    partnerSince: 2023,
    tags: ['Software Development', 'Web Applications', 'Digital Transformation'],
    featured: true,
  },
  {
    id: 2,
    name: 'Wealth Bulgaria',
    logo: '/images/companies/wblogo.webp',
    description:
      'Independent website created by a group of students in 2022 as a common project to promote free market ideas. Our team consists of young people with experience in various fields, focusing on business and investment topics.',
    industry: 'Finance',
    location: 'Bulgaria',
    website: 'https://www.wealthbulgaria.com',
    yearFounded: 2022,
    employeeCount: '1-10',
    partnershipLevel: 'Gold',
    partnerSince: 2022,
    tags: ['Finance', 'Free Market', 'Investments'],
    featured: true,
  },
  {
    id: 3,
    name: 'BUL-AI',
    logo: '/images/companies/bulailogo.png',
    description:
      'BUL-AI – Bulgarian Artificial Intelligence is a brand focused on AI development. As AI technology gains global attention and popularity, we focus on making it more accessible and usable by students and employees at all levels.',
    industry: 'Artificial Intelligence',
    location: 'Varna, Bulgaria',
    website: 'https://www.bulai.com',
    yearFounded: 2018,
    employeeCount: '10-50',
    partnershipLevel: 'Gold',
    partnerSince: 2021,
    tags: ['AI', 'Machine Learning', 'Education'],
  },
  {
    id: 6,
    name: 'Axiomy',
    logo: '/images/companies/axiomy_logo.jpg',
    description:
      'Advanced software solutions provider specializing in enterprise architecture and digital transformation.',
    industry: 'Information Technology',
    location: 'Sofia, Bulgaria',
    website: 'https://www.axiomy.example',
    yearFounded: 2018,
    employeeCount: '100-500',
    partnershipLevel: 'Silver',
    partnerSince: 2022,
    tags: ['Enterprise Architecture', 'Digital Transformation', 'Software Development'],
  },
  {
    id: 7,
    name: 'Valtech',
    logo: '/images/companies/valtech-overview.png',
    description:
      'Global digital agency providing end-to-end technology services, digital experience, and innovation solutions.',
    industry: 'Digital Services',
    location: 'Paris, France',
    website: 'https://www.valtech.example',
    yearFounded: 1993,
    employeeCount: '1,000-5,000',
    partnershipLevel: 'Gold',
    partnerSince: 2020,
    tags: ['Digital Experience', 'Innovation', 'Technology Services'],
    featured: true,
  },
  {
    id: 8,
    name: 'Besco',
    logo: '/images/companies/besco-logo-clean.png',
    description:
      'Business process optimization and consulting firm focused on operational excellence and digital workflows.',
    industry: 'Business Consulting',
    location: 'Sofia, Bulgaria',
    website: 'https://www.besco.example',
    yearFounded: 2015,
    employeeCount: '50-100',
    partnershipLevel: 'Bronze',
    partnerSince: 2023,
    tags: ['Business Process', 'Consulting', 'Operational Excellence'],
  },
  {
    id: 10,
    name: 'Oximo',
    logo: '/images/companies/oximologo.jpg',
    description:
      'Technology optimization and system integration company specializing in enterprise solutions.',
    industry: 'Information Technology',
    location: 'Sofia, Bulgaria',
    website: 'https://www.oximo.example',
    yearFounded: 2016,
    employeeCount: '100-500',
    partnershipLevel: 'Silver',
    partnerSince: 2022,
    tags: ['System Integration', 'Enterprise Solutions', 'Technology Optimization'],
  },
  {
    id: 12,
    name: 'MBrand',
    logo: '/images/companies/m-brand-500x500-transparent-2730597.png',
    description:
      'Creative marketing and branding agency specializing in digital marketing, brand identity, and creative campaigns.',
    industry: 'Digital Marketing',
    location: 'Sofia, Bulgaria',
    website: 'https://www.mbrand.example',
    yearFounded: 2014,
    employeeCount: '50-100',
    partnershipLevel: 'Bronze',
    partnerSince: 2023,
    tags: ['Digital Marketing', 'Brand Identity', 'Creative Campaigns'],
  },
] as const;

// Industry filter options
export const industryFilters = [
  { id: 'all', name: 'All Industries' },
  { id: 'software-development', name: 'Software Development' },
  { id: 'finance', name: 'Finance' },
  { id: 'artificial-intelligence', name: 'Artificial Intelligence' },
  { id: 'real-estate', name: 'Real Estate' },
  { id: 'it-cluster', name: 'IT Cluster' },
  { id: 'information-technology', name: 'Information Technology' },
  { id: 'digital-services', name: 'Digital Services' },
  { id: 'business-consulting', name: 'Business Consulting' },
  { id: 'fintech', name: 'FinTech' },
  { id: 'venture-capital', name: 'Venture Capital' },
  { id: 'digital-marketing', name: 'Digital Marketing' },
];

// Partnership level filter options
export const partnershipLevelFilters = [
  { id: 'all', name: 'All Partners' },
  { id: 'gold', name: 'Gold Partners' },
  { id: 'silver', name: 'Silver Partners' },
  { id: 'bronze', name: 'Bronze Partners' },
];
