export enum RoutePage {
  HOME = '/',
  PROJECTS = '/projects',
  PROJECT_DETAIL = '/projects/:id',
  COURSES = '/courses',
  EVENTS = '/events',
  COMPANIES = '/companies',
  ABOUT = '/about',
  LOGIN = '/login',
  REGISTER = '/register',
  WELCOME = '/welcome',
  CREATE = '/create',
  CREATE_PERSONA = '/create/persona',
  CREATE_MANUAL = '/create/manual',
  SCENARIO_DETAIL = '/scenario/:id',
  QUIZ_DETAIL = '/quiz/:id',
  COMPANY_PROFILE = '/company/profile',
  CANDIDATE_PROFILE = '/candidate/profile',
  // Legacy route - will be removed
  CREATE_PROJECT = '/create-project',
}
