export enum RoutePage {
  HOME = '/',
  PROJECTS = '/projects',
  PROJECT_DETAIL = '/projects/:id',
  COURSES = '/courses',
  EVENTS = '/events',
  COMPANIES = '/companies',
  ABOUT = '/about',
  LOGIN = '/login',
  REGISTER = '/register',
  WELCOME = '/welcome',
  DESCRIBE_CANDIDATE = '/describe-candidate',
  COMPANY_PROFILE = '/company/profile',
  CANDIDATE_PROFILE = '/candidate/profile',
}
